### ISSUE TITLE
Left bar chart mouseover acting unexpectedly

### ISSUE THREAD

**Issue by ceseale** [pbc-labs/d3fault#79]
Sometimes the color of the rect doesn't go back to the original color on mouseout. Here, red is the original color and each rect should be red because I'm not moused over. 

<img width="893" alt="screen shot 2016-01-01 at 12 30 18 pm" src="https://cloud.githubusercontent.com/assets/7860694/12072077/0d24e25c-b084-11e5-808a-849b3b59517a.png">

A mouseover before the transition completes pauses the transition similar to the Waffle Chart.

<img width="912" alt="screen shot 2016-01-01 at 12 29 48 pm" src="https://cloud.githubusercontent.com/assets/7860694/12072087/e2ab66a8-b084-11e5-9076-f4fdc1bb571e.png">

**Comment by ceseale** [comment]
@iam-peekay, @banunatina, this bug might be affecting other charts. We should hunt it down and fix before release.

**Comment by iam-peekay** [comment]
@ceseale hmm, weird.  I am using @banunatina's original tooltip implementation. It looks like it only detects mouseout events one at a time. And it you go right to left, the mousein + mouseout works properly. 

Pretty buggy. @banunatina - do you think your new tooltips implementation  (the one you included in internal) would help with this?

**Comment by banunatina** [comment]
@ceseale @iam-peekay I came across this issue when refactoring the tooltips and thought I fixed it!

I'll go back and take a look. Oddly, I've tested the transition-pausing with the bar chart and it kept moving for me. 

I think we can solve this by factoring out the tooltip to be added into the chart after the build (especially the transition) has finished.

**Comment by ceseale** [comment]
:+1:

**Comment by banunatina** [comment]
The transition-pause bug seems to happen for BarChartLeft and Waffle - any others to report? @ceseale @iam-peekay

**Comment by ceseale** [comment]
Looks like its just those two. A quick fix might be to set the mouseover and mouseout transition after the entry transitions complete.

**Comment by banunatina** [comment]
Fixed!
